### ISSUE TITLE
Fonts are buggy on Debian 12

### ISSUE THREAD

**Issue by Kitsune64** [linthesia/linthesia#85] opened 2024-08-01 08:41 UTC
Hi,
I compiled Linthesia 0.8.0 on Debian 12 64 bits today and I have buggy characters in the interface.

![Capture d’écran du 2024-08-01 10-41-30](https://github.com/user-attachments/assets/cd661ab2-a28e-491b-b311-54446dcb748b)

**Comment by rikmg** [comment] 2024-08-01 11:15
This looks similar to #65, but I'm also on debian 12  and cannot reproduce  the issue this time

What  version of SDL2_ttf are  you using?

**Comment by Kitsune64** [comment] 2024-08-01 12:58
The version inside Debian 12 packages:
**libsdl2-ttf-dev** (2.20.1+dfsg-2)

**Comment by rikmg** [comment] 2024-08-01 14:13
I also tried it with LXDE and it did not made a difference.

Just to be clear, are you compiling on the main branch? Or on the 0.8.0 tag?

**Comment by Kitsune64** [comment] 2024-08-01 15:44
the **0.8.0 tag**...I don't know how to access the Main branch. Is it the way to do?

**Comment by rikmg** [comment] 2024-08-01 16:20
the 0.8.0 tag does not have the fix, so I believe that explains it

you can either clone the repo or download a zip with the main branch code here

![imagem](https://github.com/user-attachments/assets/236d2893-2095-4a7b-8320-73021d887b36)

**Comment by Kitsune64** [comment] 2024-08-01 16:31
Thank you, it work!

**Comment by albfan** [comment] 2024-08-01 22:49
@rikmg so fixed on bd64727. should we do a 0.9.0 tag?

**Closed by albfan** 2024-08-01 22:49 UTC

**Comment by rikmg** [comment] 2024-08-02 08:12
@albfan I agree we should do a new tag, but most of the commits after 0.8.0 were fixes, so perhaps a patch version 0.8.1 ?
